import { Router } from "express";
import { auth, permit } from "../middleware/auth";
import { listJobs, createJob, removeJob  ,updateJob ,employerJobs} from "../controllers/jobs.controller";
const router = Router();
router.get("/", listJobs);
router.post("/", auth, permit("employer", "admin"), createJob);
router.delete("/:id", auth, removeJob);
router.get("/mine", auth, permit("employer"), employerJobs);
router.put("/:id", auth, updateJob);
export default router;
